### ISSUE TITLE
BROSER_FILL

### ISSUE THREAD

**Issue by Gottseidank** [vdelachaux/4DPop-Image-Buddy#2] opened 2020-09-18 13:08 UTC
La méthode BROSER_FILL fait des division par 0 à la ligne 197

Voir:
https://discuss.4d.com/t/4d-pop-does-not-load/14466/29
![9e8e788931b59c3b074706602ae7af3dc63c17f4](https://user-images.githubusercontent.com/7348458/93601011-d329f200-f9c0-11ea-98b5-f9df8148d32d.png)

**Comment by vdelachaux** [comment] 2020-09-18 14:05
Thank you for the report.
The problem is fixed in the [last commit](https://github.com/vdelachaux/4DPop-Image-Buddy/tree/master/Build/Components/4DPop%20Image%20Buddy.4dbase)

**Closed as completed by vdelachaux** 2020-09-18 14:05 UTC
